### PR TITLE
Dynamic routing

### PR DESCRIPTION
**Pull request by S3B4S**
Implemented dynamic routing and added centralised `store.json` (which could be refactored to use Vuex, but for now I just left it as json).

I don't think dynamic routing & filtering data based on the route is ideal, but I hadn't found an other way of actually building static pages so far and figured this might be a quick solution for now at least.

(Here's more about the dynamic routing I did https://vueschool.io/lessons/nuxtjs-dynamic-routes?friend=nuxt)

---
#### Below bug has been fixed.

There's a bug present, to reproduce:
- Load the site using `npm run dev`
- Select an item from the sidebar
- This should load `http://localhost:3000/categories/<category>` and show a blank page ('this page could not be found' message)
- Refresh the page
- Now the page should be loaded

No idea why it acts this way, hopefully you might know why. Anyways, I'll take a look later. Figured I'd PR this in advance so you can see what I'm planning to do with this PR.

I checked the preview of netlify's deployment, it's even more messed up there, doesn't work at all. 😐

### CODE REVIEW

**Comment by S3B4S** [comment]
Everything seems fine to merge now 👌

**Comment by lostdesign** [comment]
Great, i will test within an hour.

**Comment by lostdesign** [comment]
Should we really have `https://webgems.io/categories/{category}` - kinda preferred to have them short. As in `https://webgems.io/{category}` in order to allow people to quickly link a certain category without the need of typing too much. 

I will clone your version and try to implement the store right away, that way we could also just plug a backend anytime. Thanks again for your efforts, appreciate it.

**Comment by lostdesign** [comment]
Why is there a merge conflict? These files dont exist anymore, could you maybe fix it?

**Comment by S3B4S** [comment]
>Should we really have https://webgems.io/categories/{category} - kinda preferred to have them short.

Fair enough, I do think that's prettier too, I simply started out with a directory of `categories` since that was in the tutorial. I've already moved `_category.vue` to the root and now the urls are as `https://webgems.io/{category}`. I'll push this now.

Weird that I can't see what the conflicts are on here though 🤔, think it's updated on `master` but I deleted them so that's why. I'll merge master with this PR and fix it locally and then push that too.

**Comment by S3B4S** [comment]
I've added the updates that were applied on `master` manually to `store.json`. Should have no merge conflicts now. 👌

**Pull request merged**
