### PR TITLE
Add Web Periodic Table

### PR DESCRIPTION
**Pull request by CrazyPython**
This has "specification" because it links to specifications. The color coding shows compatibility. It also links to tutorials, guides, etc– more will be added.

### CODE REVIEW

**Comment by lostdesign** [comment]
Could you add it to only one category, so either frontend or general? A search would show two results and resources are usually bound to one category only.

**Comment by CrazyPython** [comment]
Thanks. Please squash merge.

**Comment by CrazyPython** [comment]
It is now only in one category, as you requested. Friendly reminder to merge~

**Review by lostdesign — APPROVED** [review]

**Comment by CrazyPython** [comment]
Remember to rebuild and deploy so that it shows up on https://webgems.io/frontend

Thanks,

James

**Comment by lostdesign** [comment]
;)

**Pull request merged**
